/*
 * File: app/view/AssociateViewLeftTreePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AssociateViewLeftTreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.associateviewlefttreepanel',

    requires: [
        'MyApp.view.AssociateViewLeftTreePanelViewModel',
        'MyApp.view.AssociateViewLeftTreePanelViewController',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.selection.RowModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.form.trigger.Trigger'
    ],

    controller: 'associateviewlefttreepanel',
    viewModel: {
        type: 'associateviewlefttreepanel'
    },
    height: 250,
    itemId: 'leftTreePanel',
    width: 400,
    title: 'Available',
    root: {
        text: 'Root',
        expanded: true,
        children: [
            
        ]
    },

    bind: {
        store: '{LeftTreeStore}'
    },
    columns: [
        {
            xtype: 'treecolumn',
            dataIndex: 'name',
            text: 'MyTreeColumn',
            flex: 1
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'duration',
            text: 'MyColumn'
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },
    listeners: {
        select: 'onLeftTreePanelSelect',
        leftTreeSelectEvent: 'onLeftTreePanelLeftTreeSelectEvent'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'filterField',
                    fieldLabel: 'Filter',
                    triggers: {
                        mytrigger: {
                            handler: function(field, trigger, e) {
                                field.setValue('');
                            },
                            cls: 'x-form-clear-trigger'
                        }
                    },
                    listeners: {
                        change: 'onFilterFieldChange'
                    }
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processAssociateViewLeftTreePanel(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processAssociateViewLeftTreePanel: function(config) {
        Utility.grid.addInfoCol(this);
    }

});