/*
 * File: app/view/PatientDetailSearchForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientDetailSearchForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientdetailsearchform',

    requires: [
        'MyApp.view.PatientDetailSearchFormViewModel',
        'MyApp.view.PatientDetailSearchFormViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.Text'
    ],

    controller: 'patientdetailsearchform',
    viewModel: {
        type: 'patientdetailsearchform'
    },
    height: 500,
    itemId: 'patientDetailSearchFormId',
    width: 500,
    bodyPadding: 10,
    title: 'My Form',

    listeners: {
        afterrender: 'onPatientDetailSearchFormItemIdAfterRender',
        inEdit: 'onPatientDetailSearchFormItemIdInEdit',
        saveEdit: 'onPatientDetailSearchFormItemIdSaveEdit',
        resetEdit: 'onPatientDetailSearchFormItemIdResetEdit',
        chHist: 'onPatientDetailSearchFormItemIdChHist',
        quitEdit: 'onPatientDetailSearchFormItemIdQuitEdit'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'My Fields',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'ID',
                    name: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Nom',
                    name: 'patientLName'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Prénom',
                    name: 'patientFname'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Date Naissance',
                    name: 'patientBirthday'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Numéro S.S',
                    name: 'patientSocialNumber'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Clé',
                    name: 'patientSocialKey'
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processPatientDetailSearchForm(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processPatientDetailSearchForm: function(config) {
          config.plugins = new Plugins.form.FormEditingPlugin({
                    withValidation: false,
                    showConfirmationOnSave: true
                });

                return config;
    }

});