/*
 * File: app/view/EstHasServGridViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EstHasServGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.esthasservgrid',

    requires: [
        'MyApp.view.override.EstHasServGridViewController'
    ],

    onEstablishmentCodeComboBoxEditorItemIdSelect: function(combo, record, eOpts) {

    },

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onEstHasServGridIdChHist: function() {

    },

    onEstHasServGridIdAfterRender: function(component, eOpts) {


    },

    onEstHasServGridIdInEdit: function(editor, context) {

    },

    onEstHasServGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onEstHasServGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onEstHasServGridIdAddItem: function(grid) {


    },

    onEstHasServGridIdDeleteItem: function() {

    },

    onEstHasServGridIdDuplicateItem: function() {

    },

    onEstHasServGridIdModifyItem: function() {

    },

    onEstHasServGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onEstHasServGridIdBeforeEdit: function(editor, context) {

    },

    onEstHasServGridIdCanceledit: function(editor, context) {

    },

    onEstHasServGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onEstHasServGridIdEdit: function(editor, context) {

    },

    onEstHasServGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onEstHasServGridIdValidateedit: function(editor, context) {

    }

});
