/*
 * File: app/view/RefPhyFormViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RefPhyFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.refphyform',

    requires: [
        'MyApp.view.override.RefPhyFormViewController'
    ],

    onRefPhyFormItemIdAfterRender: function(component, eOpts) {

    },

    onRefPhyFormItemIdInEdit: function(form) {

    },

    onRefPhyFormItemIdSaveEdit: function(form, promptWin, comment) {

    },

    onRefPhyFormItemIdResetEdit: function(form, promptWin) {

    },

    onRefPhyFormItemIdChHist: function(button) {

    },

    onRefPhyFormItemIdQuitEdit: function(form, promptWin) {

    },

    onRefPhyZipCodeChange: function(field, newValue, oldValue, eOpts) {

    }

});
