/*
 * File: app/view/RefPhyForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RefPhyForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.refphyform',

    requires: [
        'MyApp.view.RefPhyFormViewModel',
        'MyApp.view.RefPhyFormViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    controller: 'refphyform',
    viewModel: {
        type: 'refphyform'
    },
    height: 500,
    itemId: 'refPhyFormId',
    width: 500,
    bodyPadding: 10,
    header: false,
    title: 'Create Referring physician',

    listeners: {
        afterrender: 'onRefPhyFormItemIdAfterRender',
        inEdit: 'onRefPhyFormItemIdInEdit',
        saveEdit: 'onRefPhyFormItemIdSaveEdit',
        resetEdit: 'onRefPhyFormItemIdResetEdit',
        chHist: 'onRefPhyFormItemIdChHist',
        quitEdit: 'onRefPhyFormItemIdQuitEdit',
        boxready: 'onRefPhyFormIdBoxReady'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'identifying referring physician',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'first name',
                    name: 'referringPhysicianFName',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'last name',
                    name: 'referringPhysicianLName',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'refPhyGenderComboBoxEditorItemId',
                    fieldLabel: 'gender',
                    name: 'referringPhysicianGender',
                    allowBlank: false,
                    selectOnFocus: true,
                    displayField: 'gender',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'genderId',
                    bind: {
                        store: '{ReferringPhysicianGenderComboStore}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'refPhTitleComboBoxEditorItemId',
                    fieldLabel: 'title',
                    name: 'referringPhysicianTitle',
                    allowBlank: false,
                    selectOnFocus: true,
                    displayField: 'title',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'titleId',
                    bind: {
                        store: '{ReferringPhysicianTitleComboStore}'
                    }
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'address',
                    name: 'referringPhysicianAddress'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'refPhyZipCode',
                    fieldLabel: 'zip code',
                    name: 'referringPhysicianZipCode',
                    listeners: {
                        change: 'onRefPhyZipCodeChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cityNameComboBoxEditorItemId',
                    fieldLabel: 'city',
                    name: 'cityId',
                    selectOnFocus: true,
                    displayField: 'cityName',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'cityId',
                    bind: {
                        store: '{CityNameComboStore}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'phone',
                    name: 'referringPhysicianPhoneNumber'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'fax',
                    name: 'referringPhysicianFaxNumber'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'email',
                    name: 'referringPhysicianEmail'
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processRefPhyForm(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processRefPhyForm: function(config) {
        FormAddPlugins.addPlugins(this);
    }

});