/*
 * File: app/view/invoicing/InvoicingForm.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.invoicing.InvoicingForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.invoicing.invoicingform',

    requires: [
        'MyApp.view.invoicing.InvoicingFormViewModel',
        'MyApp.view.invoicing.InvoicingFormViewController',
        'MyApp.view.StudyVisitHasActeGrid',
        'MyApp.view.invoicing.PaymentGrid',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Fill',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.form.field.Number',
        'Ext.form.Label',
        'Ext.form.field.Checkbox'
    ],

    controller: 'invoicing.invoicingform',
    viewModel: {
        type: 'invoicing.invoicingform'
    },
    layout: 'border',
    bodyPadding: 10,
    header: false,
    title: 'My Form',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'createInvoiceBtn',
                            iconCls: 'fa fa-file-text',
                            text: 'Créer Facture',
                            listeners: {
                                click: 'onCreateInvoiceBtnClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            iconCls: 'fa fa-rss',
                            text: 'Créer F.T B2'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'validateInvoiceBtn',
                            iconCls: 'fa fa-check',
                            text: 'Valider',
                            listeners: {
                                click: 'onValidateInvoiceBtnClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            iconCls: 'fa fa-print',
                            text: 'Cerfa F.S'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            iconCls: 'fa fa-euro',
                            text: 'Dépassement'
                        }
                    ]
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'cancelInvoiceBtn',
                            iconCls: 'fa fa-share',
                            text: 'Annuler Facture',
                            listeners: {
                                click: 'onCancelInvoiceBtnClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 15
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            itemId: 'quitInvoiceBtn',
                            iconCls: 'fa fa-times',
                            text: 'Quitter',
                            listeners: {
                                click: 'onQuitInvoiceBtnClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'container',
            flex: 2,
            region: 'center',
            scrollable: true,
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Actes',
                    items: [
                        {
                            xtype: 'studyvisithasactegrid'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Montants',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    width: 150,
                                    fieldLabel: 'Patient',
                                    labelWidth: 80,
                                    name: 'invoiceAmountPatient',
                                    readOnly: true
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 180,
                                    fieldLabel: 'Remise',
                                    labelWidth: 80,
                                    name: 'invoicePatientAmountRemise'
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 250,
                                    fieldLabel: ' Dépassement patient',
                                    labelWidth: 170,
                                    name: 'invoicePatientAdditionalAmount',
                                    readOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'tbspacer',
                            height: 10
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 150,
                                    fieldLabel: 'A.M.O',
                                    labelWidth: 80,
                                    name: 'invoiceRegoAmount',
                                    readOnly: true
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 180,
                                    fieldLabel: 'A.M.C',
                                    labelWidth: 80,
                                    name: 'invoiceRegcAmount',
                                    readOnly: true
                                },
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 250,
                                    fieldLabel: 'Dépassement A.M.C',
                                    labelWidth: 170,
                                    name: 'invoiceAdditionalRegcAmount',
                                    readOnly: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Règlements',
                    items: [
                        {
                            xtype: 'invoicing.paymentgrid',
                            externalEditingPlugin: {
                                pluginId: 'gridediting',
                                onlyADM: true
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            region: 'west',
            scrollable: 'vertical',
            width: 286,
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    html: 'test<br>test',
                    itemId: 'patientFieldSet',
                    title: 'Patient'
                },
                {
                    xtype: 'fieldset',
                    html: 'test<br>test',
                    itemId: 'doctorFieldSet',
                    title: 'Médecin'
                },
                {
                    xtype: 'fieldset',
                    title: 'Informations facturations',
                    items: [
                        {
                            xtype: 'label',
                            itemId: 'modeFacturationLabel',
                            text: 'Mode de facturation'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            itemId: 'isFseCb',
                            fieldLabel: '',
                            name: 'isFse',
                            boxLabel: 'F.S.E'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            boxLabel: 'Créer une FSE sans carte vitale  (mode dégradé)'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            name: 'visitIsFree',
                            boxLabel: 'Consultation gratuite'
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: '',
                                    name: 'visitIsAmo',
                                    boxLabel: 'Tiers-payant obligatoire   '
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 44
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Pourcentage',
                                    name: 'InvoiceRegoRate'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: '',
                                    name: 'visitIsAmc',
                                    boxLabel: 'Tiers-payant complémentaire'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 10
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Pourcentage',
                                    name: 'InvoiceRegcRate'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            fieldLabel: '',
                            name: 'visitIsBillingAMC',
                            boxLabel: 'Facturation complémentaire (A.M.C)'
                        }
                    ]
                }
            ]
        }
    ]

});