/*
 * File: app/model/UserModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.UserModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean'
    ],

    validators: [
        {
            type: 'presence',
            field: 'xxFieldNameRequired'
        }
    ],

    fields: [
        {
            name: 'id'
        },
        {
            type: 'string',
            name: 'userFName'
        },
        {
            type: 'string',
            name: 'userLName'
        },
        {
            type: 'string',
            name: 'userLogin'
        },
        {
            type: 'string',
            name: 'userPass'
        },
        {
            type: 'string',
            name: 'userInitiales'
        },
        {
            type: 'string',
            name: 'userZipCode'
        },
        {
            type: 'int',
            name: 'siteCityId'
        },
        {
            type: 'string',
            name: 'userAddress'
        },
        {
            type: 'string',
            name: 'userPhone'
        },
        {
            type: 'string',
            name: 'userFax'
        },
        {
            type: 'boolean',
            name: 'active'
        },
        {
            name: 'toDelete'
        },
        {
            name: 'added'
        },
        {
            name: 'modified'
        },
        {
            name: 'notValid'
        },
        {
            name: 'addedAndValidated'
        },
        {
            type: 'string',
            name: 'cityName'
        }
    ]
});