/*
 * File: app/view/StudyGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudyGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.studygrid',

    requires: [
        'MyApp.view.StudyGridViewModel',
        'MyApp.view.StudyGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel'
    ],

    controller: 'studygrid',
    viewModel: {
        type: 'studygrid'
    },
    reference: 'studyGridRef',
    itemId: 'studyGridId',
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{StudyStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyTypeId',
            text: 'Type',
            editor: {
                xtype: 'combobox',
                itemId: 'studyTypeComboBoxEditorItemId',
                allowBlank: false,
                selectOnFocus: true,
                displayField: 'studyTypeCode',
                forceSelection: true,
                queryMode: 'local',
                valueField: 'studyTypeId',
                bind: {
                    store: '{StudyTypeComboStore}'
                }
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyCode',
            text: 'Code',
            editor: {
                xtype: 'textfield',
                itemId: 'studyCodeTextFieldItemId',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyName',
            text: 'Name',
            editor: {
                xtype: 'textfield',
                itemId: 'studyNameTextFieldItemId',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyFtNumber',
            text: 'Number FT',
            editor: {
                xtype: 'textfield',
                itemId: 'studyFtNumberTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyDuration',
            text: 'Duration',
            editor: {
                xtype: 'textfield',
                itemId: 'studyDurationTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyDaysNbToSendSms',
            text: 'Days to send SMS',
            editor: {
                xtype: 'textfield',
                itemId: 'studyDaysNbToSendSmsTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'studyIsDosimetry',
            text: 'Dosimetry',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'studyIsInjected',
            text: 'Injected',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'studyGenerateDicomWL',
            text: 'Generte DicomSegement',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'studyMultiSegment',
            text: 'Multi segment',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'active',
            text: 'Active',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyInvoiceCat',
            text: 'Invoice Cat',
            editor: {
                xtype: 'textfield',
                itemId: 'studyInvoiceCatTextFieldItemId',
                allowBlank: false
            }
        }
    ],
    listeners: {
        select: 'select',
        chHist: 'onStudyGridIdChHist',
        afterrender: 'onStudyGridIdAfterRender',
        inEdit: 'onStudyGridIdInEdit',
        resetEdit: 'onStudyGridIdResetEdit',
        saveEdit: 'onStudyGridIdSaveEdit',
        addItem: 'onStudyGridIdAddItem',
        deleteItem: 'onStudyGridIdDeleteItem',
        modifyItem: 'onStudyGridIdModifyItem',
        quitEdit: 'onStudyGridIdQuitEdit',
        beforeedit: 'onStudyGridIdBeforeEdit',
        canceledit: 'onStudyGridIdCanceledit',
        containerclick: 'onStudyGridIdContainerClick',
        edit: 'onStudyGridIdEdit',
        beforecellclick: 'onStudyGridIdBeforeCellClick',
        validateedit: 'onStudyGridIdValidateedit'
    },
    plugins: [
        {
            ptype: 'rowediting',
            pluginId: 'rowEdit',
            autoCancel: false,
            clicksToMoveEditor: 0,
            errorSummary: false
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processStudyGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processStudyGrid: function(config) {
        Plugins.grid.GridEditingPlugin.configure(this);
        this.plugins.push (
                           new Plugins.grid.GridEditingPlugin({pluginId: 'gridediting'}));

    }

});