/*
 * File: app/view/AccueilPatientForm.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AccueilPatientForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.accueilpatientform',

    requires: [
        'MyApp.view.AccueilPatientFormViewModel',
        'MyApp.view.AccueilPatientFormViewController',
        'MyApp.view.VisitForm',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.form.Panel'
    ],

    controller: 'accueilpatientform',
    viewModel: {
        type: 'accueilpatientform'
    },
    layout: 'border',
    bodyPadding: 10,
    title: 'My Form',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'container',
                    itemId: 'saveBtnCtnItemId',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'saveAccueilPatientBtn',
                            glyph: 'xf0c7@FontAwesome',
                            bind: {
                                text: '{trans.save}'
                            },
                            listeners: {
                                click: 'onSaveAccueilPatientBtnClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'visitform',
            scrollable: true,
            width: 150,
            header: false,
            region: 'center'
        }
    ]

});