/*
 * File: app/view/PatientForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientform',

    requires: [
        'MyApp.view.PatientFormViewModel',
        'MyApp.view.PatientFormViewController',
        'Ext.form.FieldSet',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Spacer',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'patientform',
    viewModel: {
        type: 'patientform'
    },
    itemId: 'patientFormId',
    bodyPadding: 10,
    header: false,
    title: 'Patient Form',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    listeners: {
        afterrender: 'onPatientFormItemIdAfterRender'
    },
    items: [
        {
            xtype: 'fieldset',
            flex: 1,
            collapsible: true,
            title: 'Identité patient',
            items: [
                {
                    xtype: 'radiogroup',
                    defaults: {
                        name: 'patientGender'
                    },
                    fieldLabel: 'Sexe',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'M',
                            inputValue: '1'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'F',
                            inputValue: '2'
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'patientTitleComboBoxEditorItemId',
                    fieldLabel: 'Civilité',
                    name: 'patientTitle',
                    allowBlank: false,
                    selectOnFocus: true,
                    displayField: 'patientTitle',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'patientTitleId',
                    bind: {
                        store: '{PatientTitleComboStore}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Nom',
                    name: 'patientLName',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Prénom',
                    name: 'patientFname',
                    allowBlank: false
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    fieldLabel: 'Date naissance',
                    name: 'patientBirthday',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Nom naissance',
                    name: 'patientBirthName'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'referringPhysicianNameComboBoxEditorItemId',
                    fieldLabel: 'Méd. Traitant',
                    name: 'referringPhysicianId',
                    selectOnFocus: true,
                    displayField: 'referringPhysicianSearch',
                    minChars: 4,
                    queryDelay: 500,
                    queryMode: 'local',
                    typeAhead: true,
                    valueField: 'referringPhysicianId',
                    bind: {
                        store: '{ReferringPhysicianNameComboStore}'
                    },
                    listeners: {
                        change: 'onReferringPhysicianNameComboBoxEditorItemIdChange'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Numéro I.N.S',
                    name: 'patientIns'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'N Sécu',
                            name: 'patientSocialNumber'
                        },
                        {
                            xtype: 'textfield',
                            width: 40,
                            fieldLabel: '',
                            name: 'patientSocialKey',
                            emptyText: 'Clé',
                            maxLength: 2
                        }
                    ]
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    fieldLabel: 'Enceinte',
                    name: 'patientPregnant',
                    boxLabel: ''
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    fieldLabel: 'Actif',
                    name: 'active',
                    boxLabel: ''
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    disabled: true,
                    fieldLabel: 'Reprise ID',
                    name: 'patientIdReprise',
                    readOnly: true
                }
            ]
        },
        {
            xtype: 'tbspacer',
            width: 10
        },
        {
            xtype: 'fieldset',
            flex: 1,
            collapsible: true,
            title: 'Coordonnées',
            items: [
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    height: 105,
                    fieldLabel: 'Adresse',
                    name: 'patientAddress'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'patientZipCodeTextFieldItemId',
                    fieldLabel: 'Code postal',
                    name: 'patientZipCode',
                    listeners: {
                        change: 'onPatientZipCodeTextFieldItemIdChange'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cityNameComboBoxEditorItemId',
                    fieldLabel: 'Commune',
                    name: 'cityId',
                    emptyText: 'Saisir au moins 4caractères',
                    selectOnFocus: true,
                    displayField: 'cityName',
                    minChars: 4,
                    queryDelay: 500,
                    queryMode: 'local',
                    typeAhead: true,
                    valueField: 'cityId',
                    bind: {
                        store: '{CityNameComboStore}'
                    },
                    listeners: {
                        change: 'onCityNameComboBoxEditorItemIdChange'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Tél',
                    name: 'patientPhoneNumber'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Portable',
                    name: 'patientMobileNumber'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'E-Mail',
                    name: 'patientEmail',
                    vtype: 'email'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'top',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'saveFormBtnItemId',
                            glyph: 'xf0c7@FontAwesome',
                            text: 'Enregistrer',
                            listeners: {
                                click: 'onSaveFormBtnItemIdClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            formBind: false,
                            itemId: 'cancelFormBtnItemId',
                            glyph: 'xf0e2@FontAwesome',
                            text: 'Annuler'
                        }
                    ]
                },
                {
                    xtype: 'tbspacer'
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processPatientForm(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processPatientForm: function(config) {

    }

});