/*
 * File: app/view/StudyVisitGridViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudyVisitGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.studyvisitgrid',

    requires: [
        'MyApp.view.override.StudyVisitGridViewController'
    ],

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onStudyVisitGridIdChHist: function() {

    },

    onStudyVisitGridIdAfterRender: function(component, eOpts) {


    },

    onStudyVisitGridIdInEdit: function(editor, context) {

    },

    onStudyVisitGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onStudyVisitGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onStudyVisitGridIdAddItem: function(grid) {


    },

    onStudyVisitGridIdDeleteItem: function() {

    },

    onStudyVisitGridIdModifyItem: function() {

    },

    onStudyVisitGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onStudyVisitGridIdBeforeEdit: function(editor, context) {

    },

    onStudyVisitGridIdCanceledit: function(editor, context) {

    },

    onStudyVisitGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onStudyVisitGridIdEdit: function(editor, context) {

    },

    onStudyVisitGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onStudyVisitGridIdValidateedit: function(editor, context) {

    }

});
