/*
 * File: app/view/WorklistGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WorklistGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.worklistgrid',

    requires: [
        'MyApp.view.WorklistGridViewModel',
        'MyApp.view.WorklistGridViewController',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.selection.RowModel'
    ],

    controller: 'worklistgrid',
    viewModel: {
        type: 'worklistgrid'
    },
    reference: 'worklistGridRef',
    itemId: 'worklistGridId',
    minWidth: 1600,
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{WorklistStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'siteName',
            text: 'Site'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            scrollable: true,
            width: '',
            dataIndex: 'worklistDate',
            text: 'Date'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'patientLastName',
            text: 'Patient'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'patientBirthDay',
            text: 'Birthday'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 150,
            dataIndex: 'worklistStudies',
            text: 'Studies'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistMedRef',
            text: 'Doctor'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistMedPresc',
            text: 'consultant Ph.'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistMedRecipient',
            text: 'Dr. Recipient'
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistDictationsNb',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistDictationsStatus',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistCrsNb',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistCrsStatus',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistCotationStatus',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistFTNum',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistPatientInfo',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: '	worklistVisitInfo',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistVisitComment',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistPatientDu',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklistFtDu',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklisCrEmailedTo',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'worklisCrMailedTo',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'patientInfos',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitInfos',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitComment',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: '	visitIsBySocialCard',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsFree',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsHospitalized',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsUrgent',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitHospitVisitNumber',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsDone',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsAmo',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitIsAmc',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitPds',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitInvoiceType',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitFtFor',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            minWidth: 100,
            dataIndex: 'visitPEC',
            text: ''
        }
    ],
    listeners: {
        select: 'select',
        chHist: 'onWorklistGridIdChHist',
        afterrender: 'onWorklistGridIdAfterRender'
    },
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    }

});