/*
 * File: app/view/DoctorGridViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DoctorGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.doctorgrid',

    requires: [
        'MyApp.view.override.DoctorGridViewController'
    ],

    onUserInitialComboBoxEditorItemIdSelect: function(combo, record, eOpts) {

    },

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onDoctorGridIdChHist: function() {

    },

    onDoctorGridIdAfterRender: function(component, eOpts) {


    },

    onDoctorGridIdInEdit: function(editor, context) {

    },

    onDoctorGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onDoctorGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onDoctorGridIdAddItem: function(grid) {


    },

    onDoctorGridIdDeleteItem: function() {

    },

    onDoctorGridIdModifyItem: function() {

    },

    onDoctorGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onDoctorGridIdBeforeEdit: function(editor, context) {

    },

    onDoctorGridIdCanceledit: function(editor, context) {

    },

    onDoctorGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onDoctorGridIdEdit: function(editor, context) {

    },

    onDoctorGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onDoctorGridIdValidateedit: function(editor, context) {

    }

});
