/*
 * File: app/model/SiteConfigModel.js
 *
 * This file was generated by Sencha Architect version 4.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.SiteConfigModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    validators: [
        {
            type: 'presence',
            field: 'xxFieldNameRequired'
        }
    ],

    fields: [
        {
            name: 'siteConfigId'
        },
        {
            name: 'siteId'
        },
        {
            name: 'siteConfigStartHour'
        },
        {
            name: 'siteConfigEndHour'
        },
        {
            name: 'siteConfigCotNuitHeureDebut'
        },
        {
            name: 'siteConfigCotNuitHeureFin'
        },
        {
            name: 'siteConfigPyxMode'
        },
        {
            name: 'siteConfigFseIsChecked'
        },
        {
            name: 'siteConfigAmoDefault'
        },
        {
            name: 'siteConfigAmcDefault'
        },
        {
            name: 'siteConfigPdsMandatory'
        },
        {
            name: 'siteConfigCotFerieAuto'
        },
        {
            name: 'siteConfigCotUrgenceAuto'
        },
        {
            name: 'siteConfigCotEnfantAuto'
        },
        {
            name: 'siteConfigCotNuitAuto'
        },
        {
            name: 'siteConfigUidSenolog'
        },
        {
            name: 'siteConfigSenologType'
        },
        {
            name: 'siteConfigTranscriptionPath'
        },
        {
            name: 'created'
        },
        {
            name: 'lastupdated'
        },
        {
            name: 'toDelete'
        },
        {
            name: 'added'
        },
        {
            name: 'modified'
        },
        {
            name: 'notValid'
        },
        {
            name: 'notValidTip'
        },
        {
            name: 'addedAndValidated'
        },
        {
            name: 'siteConfigJSDavUrl'
        },
        {
            name: 'siteConfigWordPath'
        }
    ]
});