/*
 * File: app/view/SpeechRecognitionPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SpeechRecognitionPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.speechrecognitionpanel',

    requires: [
        'MyApp.view.SpeechRecognitionPanelViewModel',
        'MyApp.view.SpeechRecognitionPanelViewController',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'speechrecognitionpanel',
    viewModel: {
        type: 'speechrecognitionpanel'
    },
    itemId: 'microImg',
    title: 'Reconnaissace vocale',

    items: [
        {
            xtype: 'htmleditor',
            height: 600,
            itemId: 'htmlEditor',
            fieldLabel: ''
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'component',
                            html: '<img src="../Common/resources/images/mic.gif" height="24" width="24"/>',
                            itemId: 'microImg'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 20
                        },
                        {
                            xtype: 'button',
                            itemId: 'recBtn',
                            text: 'Enregistrer',
                            listeners: {
                                click: 'onRecBtnClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            width: 20
                        },
                        {
                            xtype: 'button',
                            text: 'Valider'
                        }
                    ]
                }
            ]
        }
    ]

});