/*
 * File: app/view/EstablishmentFormViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EstablishmentFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.establishmentform',

    requires: [
        'MyApp.view.override.EstablishmentFormViewController'
    ],

    onEstablishmentFormItemIdInEdit: function(form) {

    },

    onEstablishmentFormItemIdSaveEdit: function(form, promptWin, comment) {

    },

    onEstablishmentFormItemIdResetEdit: function(form, promptWin) {

    },

    onEstablishmentFormItemIdChHist: function(button) {

    },

    onEstablishmentFormItemIdQuitEdit: function(form, promptWin) {

    },

    onZipCodeTextFieldChange: function(field, newValue, oldValue, eOpts) {

    },

    onEstablishmentFormIdBoxReady: function(component, width, height, eOpts) {

    }

});
