/*
 * File: app/view/scheduler/AppDetailGridViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.scheduler.AppDetailGridViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.scheduler.appdetailgrid',

    requires: [
        'Ext.data.Store'
    ],

    data: {
        trans: {
            studies: translate('studies')
        }
    },

    stores: {
        AppDetailStore: {
            model: 'MyApp.model.scheduler.AppDetailModel'
        },
        StudyComboStore: {
            model: 'MyApp.model.scheduler.StudyComboModel'
        },
        TechnicianComboStore: {
            model: 'MyApp.model.scheduler.TechnicianComboModel'
        }
    }

});