/*
 * File: app/view/SiteConfigWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SiteConfigWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.siteconfigwindow',

    requires: [
        'MyApp.view.SiteConfigWindowViewModel',
        'MyApp.view.SiteConfigWindowViewController',
        'MyApp.view.SiteConfigForm',
        'Ext.form.Panel'
    ],

    controller: 'siteconfigwindow',
    viewModel: {
        type: 'siteconfigwindow'
    },
    height: 389,
    width: 373,
    iconCls: 'fx-fa-list-alt',
    title: 'Configuration',
    modal: true,

    items: [
        {
            xtype: 'siteconfigform',
            itemId: 'siteConfigForm',
            layout: 'auto',
            header: false,
            listeners: {
                afterrender: 'onFormAfterRender',
                validateEvent: 'onFormValidateEvent',
                cancelEvent: 'onFormCancelEvent'
            }
        }
    ]

});