/*
 * File: app/view/StudyActeMainView.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudyActeMainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.studyactemainview',

    requires: [
        'MyApp.view.StudyActeMainViewViewModel',
        'MyApp.view.StudyActeMainViewViewController',
        'MyApp.view.StudyActePanel',
        'MyApp.view.StudySearchGrid',
        'Ext.grid.Panel'
    ],

    controller: 'studyactemainview',
    viewModel: {
        type: 'studyactemainview'
    },
    layout: 'border',
    header: false,
    title: 'My Panel',

    items: [
        {
            xtype: 'studyactepanel',
            flex: 2,
            itemId: 'actesPanel',
            collapsed: false,
            collapsible: false,
            region: 'center'
        },
        {
            xtype: 'studysearchgrid',
            itemId: 'studiesPanel',
            width: 200,
            animCollapse: true,
            collapsible: true,
            split: true,
            region: 'west',
            split: false,
            listeners: {
                selectionchange: 'onStudiespanelSelectionChange'
            }
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});