/*
 * File: app/view/StudySearchGrid.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudySearchGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.studysearchgrid',

    requires: [
        'MyApp.view.StudySearchGridViewModel',
        'MyApp.view.StudySearchGridViewController',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate'
    ],

    controller: 'studysearchgrid',
    viewModel: {
        type: 'studysearchgrid'
    },
    title: 'studies',

    bind: {
        store: '{StudyStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyCode',
            text: 'Study Code'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'studyName',
            text: 'Study Name'
        }
    ],
    features: [
        {
            ftype: 'grouping',
            groupHeaderTpl: [
                ' {name}'
            ]
        }
    ],
    listeners: {
        boxready: 'onGridpanelBoxReady'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processStudySearchGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processStudySearchGrid: function(config) {
        GridAddPlugins.addGridLiveSearchPlugin(this);
    }

});