/*
 * File: app/model/StudyVisitHasActeModel.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.StudyVisitHasActeModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    validators: [
        {
            type: 'presence',
            field: 'xxFieldNameRequired'
        }
    ],

    fields: [
        {
            name: 'studyVisitId'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeType'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeSuppCharge'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeSoumisEntentePrealable'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeRefundingCode'
        },
        {
            type: 'int',
            name: 'studyVisitHasActeQuantity'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeModificators'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeIsNight'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeIsMultiple'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeIsHoliday'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeIsEmergency'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeIsDomicile'
        },
        {
            name: 'studyVisitHasActeId'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeExoParticuliere'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeExceptionalRefunding'
        },
        {
            name: 'studyVisitHasActeDepense'
        },
        {
            type: 'int',
            name: 'studyVisitHasActeDenombrement'
        },
        {
            type: 'date',
            name: 'studyVisitHasActeDateEntentePrealable'
        },
        {
            type: 'int',
            name: 'studyVisitHasActeCoefficient'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeCodeAffine'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeCodeAccEntentePrealable'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeCode'
        },
        {
            type: 'int',
            name: 'studyVisitHasActeAssociationNonPrevu'
        },
        {
            type: 'boolean',
            name: 'studyVisitHasActeArchivingActeAddedAuto'
        },
        {
            type: 'float',
            name: 'studyVisitHasActeAmountDepassement'
        },
        {
            type: 'float',
            name: 'studyVisitHasActeAmount'
        },
        {
            type: 'string',
            name: 'studyVisitHasActeAcceptedModificators'
        },
        {
            type: 'int',
            name: 'studyActeId'
        },
        {
            type: 'boolean',
            name: 'active'
        },
        {
            name: 'toDelete'
        },
        {
            name: 'added'
        },
        {
            name: 'modified'
        },
        {
            name: 'notValid'
        },
        {
            name: 'addedAndValidated'
        },
        {
            type: 'int',
            name: 'studyId'
        },
        {
            name: 'studyCode'
        },
        {
            name: 'studyName'
        }
    ]
});