/*
 * File: app/view/MyPanel5.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel5', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel5',

    requires: [
        'MyApp.view.MyPanel5ViewModel',
        'MyApp.view.MyPanel5ViewController',
        'Ext.container.Container',
        'Ext.form.field.ComboBox'
    ],

    controller: 'mypanel5',
    viewModel: {
        type: 'mypanel5'
    },
    height: 250,
    style: 'font-size:10px;',
    width: 400,
    title: 'My Panel',

    items: [
        {
            xtype: 'container',
            layout: 'fit',
            items: [
                {
                    xtype: 'combobox',
                    height: 15,
                    style: 'font-seize:10px;"',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Label',
                    listeners: {
                        blur: 'onTextfieldBlur'
                    }
                }
            ]
        }
    ]

});