/*
 * File: app/view/PatientSearchCreteriaForm.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientSearchCreteriaForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientsearchcreteriaform',

    requires: [
        'MyApp.view.PatientSearchCreteriaFormViewModel',
        'MyApp.view.PatientSearchCreteriaFormViewController',
        'Ext.form.FieldSet',
        'Ext.toolbar.Spacer',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'patientsearchcreteriaform',
    viewModel: {
        type: 'patientsearchcreteriaform'
    },
    bodyPadding: 10,
    title: 'My Form',

    items: [
        {
            xtype: 'fieldset',
            collapsible: true,
            title: 'Cliquer sur la touche "Entrée" pour lancer la recherche',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: '',
                            name: 'patientLName',
                            emptyText: 'Nom',
                            listeners: {
                                specialkey: 'onTextfieldSpecialkey'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 10
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: '',
                            name: 'patientFname',
                            emptyText: 'Prenom',
                            listeners: {
                                specialkey: 'onTextfieldSpecialkey'
                            }
                        }
                    ]
                },
                {
                    xtype: 'tbspacer',
                    height: 5
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            flex: 1,
                            fieldLabel: '',
                            name: 'patientBirthday',
                            emptyText: 'Date de naissance',
                            format: 'd/m/Y',
                            submitFormat: 'Y-m-d',
                            listeners: {
                                specialkey: 'onDatefieldSpecialkey'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 10
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: '',
                            name: 'patientSocialNumber',
                            emptyText: 'Numéro s.s',
                            listeners: {
                                specialkey: 'onTextfieldSpecialkey'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 10
                        },
                        {
                            xtype: 'textfield',
                            width: 50,
                            fieldLabel: '',
                            name: 'patientSocialKey',
                            emptyText: 'Clé',
                            listeners: {
                                specialkey: 'onTextfieldSpecialkey'
                            }
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    margin: '5 0 0 0 0',
                    fieldLabel: '',
                    name: 'patientVisitNumber',
                    emptyText: 'Numéro de séjour'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    margin: '5 0 0 0',
                    fieldLabel: '',
                    name: 'establishmentId',
                    emptyText: 'Etablissement emetteur',
                    queryMode: 'local'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            itemId: 'patientSearchBtnItemId',
                            icon: '',
                            iconCls: 'fa fa-search',
                            text: 'Rechercher',
                            listeners: {
                                click: 'onPatientSearchBtnItemIdClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        boxready: 'onFormBoxReady'
    }

});