/*
 * File: app/view/PatientDetailSearchFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientDetailSearchFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.patientdetailsearchform',

    requires: [
        'MyApp.view.override.PatientDetailSearchFormViewController'
    ],

    onTextfieldSpecialkey: function(field, e, eOpts) {

    },

    onTextfieldSpecialkey: function(field, e, eOpts) {

    },

    onDatefieldSpecialkey: function(field, e, eOpts) {

    },

    onTextfieldSpecialkey: function(field, e, eOpts) {

    },

    onTextfieldSpecialkey: function(field, e, eOpts) {

    },

    onPatientSearchBtnItemIdClick: function(button, e, eOpts) {

    },

    onPatientSearchGridItemIdItemDblClick: function(dataview, record, item, index, e, eOpts) {

    },

    onNouveauPatientBtnItemIdClick: function(button, e, eOpts) {

    },

    onAccueilPatientBtnItemIdClick: function(button, e, eOpts) {

    },

    onHistoriquePatientBtnItemIdClick: function(button, e, eOpts) {

    },

    onFichePatientBtnItemIdClick: function(button, e, eOpts) {

    },

    onPatientSearchGridItemIdSelectionChange: function(model, selected, eOpts) {

    }

});
