/*
 * File: app/view/PatientFormViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.patientform',

    requires: [
        'MyApp.view.override.PatientFormViewController'
    ],

    onPatientFormItemIdAfterRender: function(component, eOpts) {

    },

    onPatientZipCodeTextFieldItemIdChange: function(field, newValue, oldValue, eOpts) {

    },

    onCityNameComboBoxEditorItemIdChange: function(field, newValue, oldValue, eOpts) {

    },

    onSaveFormBtnItemIdClick: function(button, e, eOpts) {

    }

});
