/*
 * File: app/view/PatientSearchGridPanel.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PatientSearchGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.patientsearchgridpanel',

    requires: [
        'MyApp.view.PatientSearchGridPanelViewModel',
        'MyApp.view.PatientSearchGridPanelViewController',
        'Ext.view.Table',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    controller: 'patientsearchgridpanel',
    viewModel: {
        type: 'patientsearchgridpanel'
    },
    scrollable: true,
    title: '',
    hideHeaders: true,

    bind: {
        store: '{PatientSearchDetailStore}'
    },
    viewConfig: {
        itemId: 'searchGridItemId'
    },
    columns: [
        {
            xtype: 'templatecolumn',
            flex: 1,
            tpl: [
                '<img src="../Common/resources/images/{patientHl7Gender}.png"/>  ',
                '                                <span style="font-weight:bold"> {patientHl7LName} {patientHl7Fname}',
                '                                {[Ext.Date.format(values.patientHl7Birthday, "d/m/Y")]}',
                '</span><br />Adresse : {patientHl7Address}<br/>{patientHl7ZipCode} {patientHl7cityName}',
                '  '
            ],
            dataIndex: 'patientHl7LName',
            text: 'Résultats de la recherche'
        }
    ],
    listeners: {
        itemdblclick: 'onPatientSearchGridItemIdItemDblClick',
        selectionchange: 'onPatientSearchGridItemIdSelectionChange'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'nouveauPatientBtnItemId',
                            text: 'Nouveau patient',
                            listeners: {
                                click: 'onNouveauPatientBtnItemIdClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            disabled: true,
                            itemId: 'accueilPatientBtnItemId',
                            text: 'Accueillir patient sélectionné',
                            listeners: {
                                click: 'onAccueilPatientBtnItemIdClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            disabled: true,
                            itemId: 'historiquePatientBtnItemId',
                            text: 'Accès historique',
                            listeners: {
                                click: 'onHistoriquePatientBtnItemIdClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            disabled: true,
                            itemId: 'fichePatientBtnItemId',
                            text: 'Accès Fiche patient',
                            listeners: {
                                click: 'onFichePatientBtnItemIdClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});