/*
 * File: app/view/RecForm.js
 *
 * This file was generated by Sencha Architect version 4.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RecForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.recform',

    requires: [
        'MyApp.view.RecFormViewModel',
        'MyApp.view.RecFormViewController',
        'Ext.form.FieldSet',
        'Ext.ux.inputs.AdvancedCombobox',
        'Ext.form.field.Radio',
        'Ext.toolbar.Spacer'
    ],

    controller: 'recform',
    viewModel: {
        type: 'recform'
    },
    itemId: 'recFormId',
    scrollable: 'true',
    bodyPadding: 10,
    title: 'My Form',

    listeners: {
        inEdit: 'onRecFormItemIdInEdit',
        saveEdit: 'onRecFormItemIdSaveEdit',
        resetEdit: 'onRecFormItemIdResetEdit',
        chHist: 'onRecFormItemIdChHist',
        quitEdit: 'onRecFormItemIdQuitEdit',
        boxready: 'onRecFormIdBoxReady'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'A.M.C',
            items: [
                {
                    xtype: 'advancedCombobox',
                    anchor: '100%',
                    itemId: 'amcIdComboBoxEditorItemId',
                    fieldLabel: 'Organisme AMC',
                    name: 'amcId',
                    selectOnFocus: true,
                    displayField: 'amcId',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'amcName',
                    bind: {
                        store: '{AmcIdComboStore}'
                    }
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            fieldLabel: 'Mode',
                            name: 'regcMode',
                            value: 'U',
                            boxLabel: 'Unique'
                        },
                        {
                            xtype: 'tbspacer',
                            width: 10
                        },
                        {
                            xtype: 'radiofield',
                            fieldLabel: '',
                            name: 'regcMode',
                            value: 'S',
                            boxLabel: 'Séparé'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'N° mutuelle',
                    name: 'regcNumMutuelle'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'N° AMC',
                    name: 'regcNumAMC'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'regcFormuleComboBoxEditorItemId',
                    fieldLabel: 'Formule',
                    name: 'regcFormule',
                    selectOnFocus: true,
                    displayField: 'regcFormule',
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'id',
                    bind: {
                        store: '{RegcFormuleComboStore}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Du ',
                    name: 'regcDu'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Au',
                    name: 'regcAu'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'N° Adherent',
                    name: 'regcNumAdherent'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Type convention',
                    name: 'regcTypeConv'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Attestation présenté',
                    name: 'regcAttestationPresentee'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Indice traitement',
                    name: 'regcIndicTraitement'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Aiguillage STS',
                    name: 'regcSts'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Routage',
                    name: 'regcRoutage'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Hote',
                    name: 'regcHote'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Domaine',
                    name: 'regcDomaine'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Critère secondaire',
                    name: 'regcCritereSecondaire'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Garanties mutuelle',
                    name: 'regcGarantieMut'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'PEC AMC',
                    name: 'regcPecAMC'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Identification assuré AMC',
                    name: 'regcAssureAMC'
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processRecForm(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processRecForm: function(config) {
        FormAddPlugins.addPlugins(this);
    }

});