/*
 * File: app/view/ReportTemplateGrid.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ReportTemplateGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.reporttemplategrid',

    requires: [
        'MyApp.view.ReportTemplateGridViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Boolean',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    viewModel: {
        type: 'reporttemplategrid'
    },
    title: 'My Grid Panel',

    bind: {
        store: '{ReportTemplateGridStore}'
    },
    columns: [
        {
            xtype: 'numbercolumn',
            dataIndex: 'doctorId',
            text: 'Doctor Id',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'reportTemplateName',
            text: 'name',
            editor: {
                xtype: 'textfield'
            }
        },
        {
            xtype: 'booleancolumn',
            dataIndex: 'reportTemplateContentIsHtml',
            text: 'is HTML',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'booleancolumn',
            dataIndex: 'reportTemplateIsPublic',
            text: 'public',
            editor: {
                xtype: 'checkboxfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'doctor',
            text: 'doctor',
            editor: {
                xtype: 'combobox'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            text: 'add'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            text: 'modify'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            text: 'delete'
                        }
                    ]
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            text: 'save'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'button',
                            text: 'cancel'
                        }
                    ]
                }
            ]
        }
    ]

});