/*
 * File: app/view/ReportFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ReportFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.reportform',

    requires: [
        'MyApp.view.override.ReportFormViewController'
    ],

    onShortcutsComboItemIdSelect: function(combo, record, eOpts) {

    },

    onShortcutNameTextFieldItemIdChange: function(field, newValue, oldValue, eOpts) {

    },

    onAddShortcutBtnItemIdClick: function(button, e, eOpts) {

    },

    onGridpanelSelectReportEvent: function(gridpanel) {

    },

    onGridpanelAddReportEvent: function(gridpanel) {

    },

    onGridpanelSaveReportEvent: function(gridpanel) {

    },

    onGridpanelValidateReportEvent: function(gridpanel) {

    },

    onGridpanelReviewReportEvent: function(gridpanel) {

    },

    onFormAfterRender: function(component, eOpts) {

    }

});
