/*
 * File: app/view/VisitRefPhGridViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.VisitRefPhGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.visitrefphgrid',

    requires: [
        'MyApp.view.override.VisitRefPhGridViewController'
    ],

    onReferringPhysicianSearchComboBoxEditorItemIdSelect: function(combo, record, eOpts) {

    },

    onReferringPhysicianSearchComboBoxEditorItemIdChange: function(field, newValue, oldValue, eOpts) {

    },

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onVisitRefPhGridIdChHist: function() {

    },

    onVisitRefPhGridIdAfterRender: function(component, eOpts) {


    },

    onVisitRefPhGridIdInEdit: function(editor, context) {

    },

    onVisitRefPhGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onVisitRefPhGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onVisitRefPhGridIdAddItem: function(grid) {


    },

    onVisitRefPhGridIdDeleteItem: function() {

    },

    onVisitRefPhGridIdDuplicateItem: function() {

    },

    onVisitRefPhGridIdModifyItem: function() {

    },

    onVisitRefPhGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onVisitRefPhGridIdBeforeEdit: function(editor, context) {

    },

    onVisitRefPhGridIdCanceledit: function(editor, context) {

    },

    onVisitRefPhGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onVisitRefPhGridIdEdit: function(editor, context) {

    },

    onVisitRefPhGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onVisitRefPhGridIdValidateedit: function(editor, context) {

    }

});
