/*
 * File: app/view/VisitSimplifiedForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.VisitSimplifiedForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.visitsimplifiedform',

    requires: [
        'MyApp.view.VisitSimplifiedFormViewModel',
        'MyApp.view.VisitSimplifiedFormViewController',
        'MyApp.view.StudyVisitGrid',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.form.field.Checkbox',
        'Ext.grid.Panel'
    ],

    controller: 'visitsimplifiedform',
    viewModel: {
        type: 'visitsimplifiedform'
    },
    itemId: 'visitSimplifiedFormId',
    bodyPadding: 10,
    title: 'My Form',

    listeners: {
        afterrender: 'onVisitSimplifiedFormItemIdAfterRender',
        saveEdit: 'onVisitSimplifiedFormItemIdSaveEdit',
        chHist: 'onVisitSimplifiedFormItemIdChHist',
        quitEdit: 'onVisitSimplifiedFormItemIdQuitEdit'
    },
    items: [
        {
            xtype: 'fieldset',
            bind: {
                title: '{trans.visitInformation}'
            },
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'siteIdComboBoxItemId',
                    name: 'siteId',
                    value: '1',
                    allowBlank: false,
                    displayField: 'siteCode',
                    forceSelection: true,
                    queryMode: 'local',
                    typeAhead: true,
                    valueField: 'siteId',
                    bind: {
                        fieldLabel: '{trans.site}',
                        store: '{SiteComboStore}'
                    }
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    name: 'visitDate',
                    allowBlank: false,
                    bind: {
                        fieldLabel: '{trans.date}'
                    }
                },
                {
                    xtype: 'timefield',
                    anchor: '100%',
                    name: 'visitTime',
                    allowBlank: false,
                    bind: {
                        fieldLabel: '{trans.hour}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'doctorComboBoxItemId',
                    name: 'doctorId',
                    allowBlank: false,
                    selectOnFocus: true,
                    displayField: 'userLName',
                    displayTpl: [
                        '<tpl for=".">{userLName} {userFName}</tpl>'
                    ],
                    forceSelection: true,
                    queryMode: 'local',
                    valueField: 'doctorId',
                    bind: {
                        fieldLabel: '{trans.doctor}',
                        store: '{DoctorComboStore}'
                    },
                    listConfig: {
                        xtype: 'boundlist',
                        itemSelector: 'div',
                        itemTpl: [
                            ' {userLName} {userFName}'
                        ]
                    },
                    listeners: {
                        change: 'onDoctorComboBoxItemIdChange'
                    }
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    name: 'visitIsFree',
                    boxLabel: '',
                    bind: {
                        fieldLabel: '{trans.free}'
                    }
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    name: 'visitIsHospitalized',
                    boxLabel: '',
                    bind: {
                        fieldLabel: '{trans.hospitalized}'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    name: 'visitHospitVisitNumber',
                    bind: {
                        fieldLabel: '{trans.hospitVisitNumber}'
                    }
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    name: 'visitIsUrgent',
                    boxLabel: '',
                    bind: {
                        fieldLabel: '{trans.emergency}'
                    }
                },
                {
                    xtype: 'studyvisitgrid',
                    hideHeaders: false,
                    externalEditingPlugin: {
                        pluginId: 'gridediting',
                        onlyADM: true
                    }
                }
            ]
        }
    ]

});