/*
 * File: app/view/VisitSimplifiedFormViewModel.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.VisitSimplifiedFormViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.visitsimplifiedform',

    requires: [
        'Ext.data.Store'
    ],

    data: {
        trans: {
            free: translate('free'),
            visitInformation: translate('visitInformation'),
            date: translate('date'),
            hospitalized: translate('hospitalized'),
            emergency: translate('emergency'),
            studies: translate('studies'),
            price: translate('price'),
            device: translate('device'),
            hospitVisitNumber: translate('hospitVisitNumber'),
            addStudy: translate('addStudy'),
            study: translate('study'),
            hour: translate('hour'),
            site: translate('site'),
            doctor: translate('doctor')
        }
    },

    stores: {
        VisitPdsComboStore: {
            model: 'MyApp.model.VisitPdsComboModel'
        },
        StudyVisitStore: {
            model: 'MyApp.model.StudyVisitModel'
        },
        StudyComboStore: {
            model: 'MyApp.model.StudyComboModel'
        },
        SiteComboStore: {
            model: 'MyApp.model.SiteComboModel'
        },
        DoctorComboStore: {
            model: 'MyApp.model.DoctorComboModel'
        }
    }

});