/*
 * File: app/model/RegoModel.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.RegoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean',
        'Ext.data.field.Date',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            name: 'regoId'
        },
        {
            name: 'patientId'
        },
        {
            name: 'visitId'
        },
        {
            name: 'regoNumSecu'
        },
        {
            name: 'regoCleSecu'
        },
        {
            name: 'regoCodeRegime'
        },
        {
            name: 'regoCodeCaisse'
        },
        {
            name: 'regoCodeCentre'
        },
        {
            name: 'regoDateNaiss'
        },
        {
            name: 'regoTauxRemboursement'
        },
        {
            type: 'boolean',
            name: 'regoCmu'
        },
        {
            type: 'boolean',
            name: 'regoAld'
        },
        {
            type: 'boolean',
            name: 'regoForcageAld'
        },
        {
            type: 'boolean',
            name: 'regoAutrePec'
        },
        {
            type: 'boolean',
            name: 'regoAme'
        },
        {
            type: 'boolean',
            name: 'regoAmeComp'
        },
        {
            type: 'boolean',
            name: 'regoInvalidite'
        },
        {
            type: 'boolean',
            name: 'regoDepistage'
        },
        {
            type: 'boolean',
            name: 'regoAccDroitCommun'
        },
        {
            type: 'date',
            name: 'regoDateAccDroitCommun'
        },
        {
            type: 'boolean',
            name: 'regoMaternite'
        },
        {
            type: 'boolean',
            name: 'regoForcageMaternite'
        },
        {
            type: 'date',
            name: 'regoDateMaternite'
        },
        {
            type: 'boolean',
            name: 'regoSmg'
        },
        {
            type: 'boolean',
            name: 'regoRegimeAlsace'
        },
        {
            name: 'regoQualiteBenef'
        },
        {
            type: 'int',
            name: 'regoRangGemBenef'
        },
        {
            name: 'regoNomAssure'
        },
        {
            name: 'regoPrenomAssure'
        },
        {
            type: 'int',
            name: 'regoRangGemAssure'
        },
        {
            name: 'regoCodeCouverture'
        },
        {
            name: 'regoFns'
        },
        {
            type: 'date',
            name: 'regoDu'
        },
        {
            type: 'date',
            name: 'regoAu'
        },
        {
            type: 'boolean',
            name: 'active'
        }
    ]
});