/*
 * File: app/model/VisitModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.VisitModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Date',
        'Ext.data.field.Boolean',
        'Ext.data.field.Integer'
    ],

    validators: [
        {
            type: 'presence',
            field: 'xxFieldNameRequired'
        }
    ],

    fields: [
        {
            type: 'date',
            name: 'visitDate'
        },
        {
            name: 'visitTime'
        },
        {
            type: 'boolean',
            name: 'visitIsBySocialCard'
        },
        {
            type: 'boolean',
            name: 'visitIsFree'
        },
        {
            type: 'boolean',
            name: 'visitFtIsFree'
        },
        {
            type: 'boolean',
            name: 'visitIsHospitalized'
        },
        {
            type: 'boolean',
            name: 'visitIsUrgent'
        },
        {
            type: 'boolean',
            name: 'visitHospitVisitNumber'
        },
        {
            type: 'boolean',
            name: 'visitIsAmo'
        },
        {
            type: 'boolean',
            name: 'visitIsAmc'
        },
        {
            type: 'boolean',
            name: 'visitIsBillingAMC'
        },
        {
            name: 'visitPds'
        },
        {
            type: 'int',
            name: 'visitAldResponse'
        },
        {
            type: 'int',
            name: 'visitInvoiceType'
        },
        {
            type: 'int',
            name: 'visitFtFor'
        },
        {
            name: 'visitPacsId'
        },
        {
            type: 'boolean',
            name: 'visitIsDone'
        },
        {
            type: 'int',
            name: 'visitLastCrStatus'
        },
        {
            type: 'int',
            name: 'visitLastCotationStatus'
        },
        {
            name: 'toDelete'
        },
        {
            name: 'added'
        },
        {
            name: 'modified'
        },
        {
            name: 'notValid'
        },
        {
            name: 'addedAndValidated'
        },
        {
            name: 'patientId'
        },
        {
            name: 'visitId'
        },
        {
            type: 'int',
            name: 'siteId'
        },
        {
            type: 'int',
            name: 'doctorId'
        }
    ]
});