/*
 * File: app/view/MyPanelCotation.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanelCotation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanelcotation',

    requires: [
        'MyApp.view.MyPanelCotationViewModel',
        'MyApp.view.MyPanelCotationViewController',
        'Ext.button.Button'
    ],

    controller: 'mypanelcotation',
    viewModel: {
        type: 'mypanelcotation'
    },
    height: 250,
    width: 400,
    title: 'My Panel',

    items: [
        {
            xtype: 'button',
            text: 'MyButton',
            listeners: {
                click: 'onButtonClick'
            }
        }
    ]

});