/*
 * File: app/view/DeviceTypeGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DeviceTypeGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.devicetypegrid',

    requires: [
        'MyApp.view.DeviceTypeGridViewModel',
        'MyApp.view.DeviceTypeGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel'
    ],

    controller: 'devicetypegrid',
    viewModel: {
        type: 'devicetypegrid'
    },
    reference: 'deviceTypeGridRef',
    itemId: 'deviceTypeGridId',
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{DeviceTypeStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'deviceTypeName',
            text: 'Device',
            editor: {
                xtype: 'textfield',
                itemId: 'deviceTypeNameTextFieldItemId',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'deviceTypeCode',
            text: 'Type',
            editor: {
                xtype: 'textfield',
                itemId: 'deviceTypeCodeTextFieldItemId',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'active',
            text: 'Active',
            editor: {
                xtype: 'checkboxfield'
            }
        }
    ],
    listeners: {
        select: 'select',
        chHist: 'onDeviceTypeGridIdChHist',
        afterrender: 'onDeviceTypeGridIdAfterRender',
        inEdit: 'onDeviceTypeGridIdInEdit',
        resetEdit: 'onDeviceTypeGridIdResetEdit',
        saveEdit: 'onDeviceTypeGridIdSaveEdit',
        addItem: 'onDeviceTypeGridIdAddItem',
        deleteItem: 'onDeviceTypeGridIdDeleteItem',
        modifyItem: 'onDeviceTypeGridIdModifyItem',
        quitEdit: 'onDeviceTypeGridIdQuitEdit',
        beforeedit: 'onDeviceTypeGridIdBeforeEdit',
        canceledit: 'onDeviceTypeGridIdCanceledit',
        containerclick: 'onDeviceTypeGridIdContainerClick',
        edit: 'onDeviceTypeGridIdEdit',
        beforecellclick: 'onDeviceTypeGridIdBeforeCellClick',
        validateedit: 'onDeviceTypeGridIdValidateedit'
    },
    plugins: [
        {
            ptype: 'rowediting',
            pluginId: 'rowEdit',
            autoCancel: false,
            clicksToMoveEditor: 0,
            errorSummary: false
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processDeviceTypeGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processDeviceTypeGrid: function(config) {
        Plugins.grid.GridEditingPlugin.configure(this);
        this.plugins.push (
                           new Plugins.grid.GridEditingPlugin({pluginId: 'gridediting'}));

    }

});