/*
 * File: app/view/DeviceGridViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DeviceGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.devicegrid',

    requires: [
        'MyApp.view.override.DeviceGridViewController'
    ],

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onDeviceGridIdChHist: function() {

    },

    onDeviceGridIdAfterRender: function(component, eOpts) {


    },

    onDeviceGridIdInEdit: function(editor, context) {

    },

    onDeviceGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onDeviceGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onDeviceGridIdAddItem: function(grid) {


    },

    onDeviceGridIdDeleteItem: function() {

    },

    onDeviceGridIdModifyItem: function() {

    },

    onDeviceGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onDeviceGridIdBeforeEdit: function(editor, context) {

    },

    onDeviceGridIdCanceledit: function(editor, context) {

    },

    onDeviceGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onDeviceGridIdEdit: function(editor, context) {

    },

    onDeviceGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onDeviceGridIdValidateedit: function(editor, context) {

    }

});
