/*
 * File: app/view/UserGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.usergrid',

    requires: [
        'MyApp.view.UserGridViewModel',
        'MyApp.view.UserGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel'
    ],

    controller: 'usergrid',
    viewModel: {
        type: 'usergrid'
    },
    reference: 'userGridRef',
    itemId: 'userGridId',
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{UserGridStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'addressId',
            text: 'Address ID',
            editor: {
                xtype: 'textfield',
                itemId: 'addressIdTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'userFName',
            text: 'User First Name',
            editor: {
                xtype: 'textfield',
                itemId: 'userFNameTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'userLName',
            text: 'User Last Name',
            editor: {
                xtype: 'textfield',
                itemId: 'userLNameTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'userLogin',
            text: 'Login',
            editor: {
                xtype: 'textfield',
                itemId: 'userLoginTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'userPass',
            text: 'PassWord',
            editor: {
                xtype: 'textfield',
                itemId: 'userPassTextFieldItemId',
                inputType: 'password'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'userInitiales',
            text: 'Initiales',
            editor: {
                xtype: 'textfield',
                itemId: 'userInitialesTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'active',
            text: 'Active',
            editor: {
                xtype: 'checkboxfield'
            }
        }
    ],
    listeners: {
        select: 'select',
        chHist: 'onUserGridIdChHist',
        afterrender: 'onUserGridIdAfterRender',
        inEdit: 'onUserGridIdInEdit',
        resetEdit: 'onUserGridIdResetEdit',
        saveEdit: 'onUserGridIdSaveEdit',
        addItem: 'onUserGridIdAddItem',
        deleteItem: 'onUserGridIdDeleteItem',
        modifyItem: 'onUserGridIdModifyItem',
        quitEdit: 'onUserGridIdQuitEdit',
        beforeedit: 'onUserGridIdBeforeEdit',
        canceledit: 'onUserGridIdCanceledit',
        containerclick: 'onUserGridIdContainerClick',
        edit: 'onUserGridIdEdit',
        beforecellclick: 'onUserGridIdBeforeCellClick',
        validateedit: 'onUserGridIdValidateedit'
    },
    plugins: [
        {
            ptype: 'rowediting',
            pluginId: 'rowEdit',
            autoCancel: false,
            clicksToMoveEditor: 0,
            errorSummary: false
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processUserGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processUserGrid: function(config) {
        Plugins.grid.GridEditingPlugin.configure(this);
        this.plugins.push (
                           new Plugins.grid.GridEditingPlugin({pluginId: 'gridediting'}));

    }

});