/*
 * File: app/view/StudyVisitHasActeGridViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudyVisitHasActeGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.studyvisithasactegrid',

    requires: [
        'MyApp.view.override.StudyVisitHasActeGridViewController'
    ],

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onStudyVisitHasActeGridIdChHist: function() {

    },

    onStudyVisitHasActeGridIdAfterRender: function(component, eOpts) {


    },

    onStudyVisitHasActeGridIdInEdit: function(editor, context) {

    },

    onStudyVisitHasActeGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onStudyVisitHasActeGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onStudyVisitHasActeGridIdAddItem: function(grid) {

        Ext.create('Common.ux.window.FullScreenWindow',{
            title:'Replace',
            items:{
                xtype:'studyvisitgrid',
                region:'center'


            }


        }).show();

    },

    onStudyVisitHasActeGridIdDeleteItem: function() {

    },

    onStudyVisitHasActeGridIdModifyItem: function() {

    },

    onStudyVisitHasActeGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onStudyVisitHasActeGridIdBeforeEdit: function(editor, context) {

    },

    onStudyVisitHasActeGridIdCanceledit: function(editor, context) {

    },

    onStudyVisitHasActeGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onStudyVisitHasActeGridIdEdit: function(editor, context) {

    },

    onStudyVisitHasActeGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onStudyVisitHasActeGridIdValidateedit: function(editor, context) {

    }

});
