/*
 * File: app/view/UserCatGridViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UserCatGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.usercatgrid',

    requires: [
        'MyApp.view.override.UserCatGridViewController'
    ],

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onUserCatGridIdChHist: function() {

    },

    onUserCatGridIdAfterRender: function(component, eOpts) {


    },

    onUserCatGridIdInEdit: function(editor, context) {

    },

    onUserCatGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onUserCatGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onUserCatGridIdAddItem: function(grid) {


    },

    onUserCatGridIdDeleteItem: function() {

    },

    onUserCatGridIdModifyItem: function() {

    },

    onUserCatGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onUserCatGridIdBeforeEdit: function(editor, context) {

    },

    onUserCatGridIdCanceledit: function(editor, context) {

    },

    onUserCatGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onUserCatGridIdEdit: function(editor, context) {

    },

    onUserCatGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onUserCatGridIdValidateedit: function(editor, context) {

    }

});
