/*
 * File: app/view/DeviceGrid.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DeviceGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.devicegrid',

    requires: [
        'MyApp.view.DeviceGridViewModel',
        'MyApp.view.DeviceGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel'
    ],

    controller: 'devicegrid',
    viewModel: {
        type: 'devicegrid'
    },
    reference: 'deviceGridRef',
    itemId: 'deviceGridId',
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{DeviceStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'deviceName',
            text: 'Device Name',
            editor: {
                xtype: 'textfield',
                itemId: 'deviceNameTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'deviceModel',
            text: 'Device Model',
            editor: {
                xtype: 'textfield',
                itemId: 'deviceModelTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'deviceAET',
            text: 'Device AET',
            editor: {
                xtype: 'textfield',
                itemId: 'deviceAETTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            dataIndex: 'active',
            text: 'Active',
            editor: {
                xtype: 'checkboxfield'
            }
        }
    ],
    listeners: {
        select: 'select',
        chHist: 'onDeviceGridIdChHist',
        afterrender: 'onDeviceGridIdAfterRender',
        inEdit: 'onDeviceGridIdInEdit',
        resetEdit: 'onDeviceGridIdResetEdit',
        saveEdit: 'onDeviceGridIdSaveEdit',
        addItem: 'onDeviceGridIdAddItem',
        deleteItem: 'onDeviceGridIdDeleteItem',
        modifyItem: 'onDeviceGridIdModifyItem',
        quitEdit: 'onDeviceGridIdQuitEdit',
        beforeedit: 'onDeviceGridIdBeforeEdit',
        canceledit: 'onDeviceGridIdCanceledit',
        containerclick: 'onDeviceGridIdContainerClick',
        edit: 'onDeviceGridIdEdit',
        beforecellclick: 'onDeviceGridIdBeforeCellClick',
        validateedit: 'onDeviceGridIdValidateedit'
    },
    plugins: [
        {
            ptype: 'rowediting',
            pluginId: 'rowEdit',
            autoCancel: false,
            clicksToMoveEditor: 0,
            errorSummary: false
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processDeviceGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processDeviceGrid: function(config) {
        Plugins.grid.GridEditingPlugin.configure(this);
        this.plugins.push (
                           new Plugins.grid.GridEditingPlugin({pluginId: 'gridediting'}));

    }

});