/*
 * File: app/model/FiscalYearModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.FiscalYearModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.Boolean',
        'Ext.data.field.String'
    ],

    validators: [
        {
            type: 'presence',
            field: 'xxFieldNameRequired'
        }
    ],

    fields: [
        {
            type: 'int',
            name: 'fiscalYearId'
        },
        {
            type: 'int',
            name: 'siteGroupId'
        },
        {
            name: 'fiscalYearName'
        },
        {
            type: 'date',
            name: 'fiscalYearStartDate'
        },
        {
            type: 'date',
            name: 'fiscalYearEndDate'
        },
        {
            type: 'boolean',
            name: 'fiscalYearClosed'
        },
        {
            type: 'boolean',
            name: 'active'
        },
        {
            type: 'string',
            name: 'siteGroupName'
        },
        {
            name: 'toDelete'
        },
        {
            name: 'added'
        },
        {
            name: 'modified'
        },
        {
            name: 'notValid'
        },
        {
            name: 'addedAndValidated'
        }
    ]
});