/*
 * File: app/view/DoctorHasExamensViewSelectedTreePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DoctorHasExamensViewSelectedTreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.doctorhasexamensviewselectedtreepanel',

    requires: [
        'MyApp.view.DoctorHasExamensViewSelectedTreePanelViewModel',
        'MyApp.view.DoctorHasExamensViewSelectedTreePanelViewController',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.form.field.Text',
        'Ext.selection.RowModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.trigger.Trigger'
    ],

    controller: 'doctorhasexamensviewselectedtreepanel',
    viewModel: {
        type: 'doctorhasexamensviewselectedtreepanel'
    },
    height: 250,
    itemId: 'selectedTreePanel',
    width: 400,
    title: 'Title',
    hideHeaders: true,
    root: {
        text: 'Root',
        expanded: true,
        children: [
            
        ]
    },
    rootVisible: false,

    bind: {
        store: '{SelectedTreeStore}'
    },
    columns: [
        {
            xtype: 'treecolumn',
            dataIndex: 'name',
            text: 'MyTreeColumn1',
            flex: 1
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'duration',
            text: 'Durée',
            editor: {
                xtype: 'textfield',
                itemId: 'durationTextFieldItemId'
            }
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'MULTI'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'filterField',
                    fieldLabel: 'Filter',
                    triggers: {
                        mytrigger1: {
                            handler: function(field, trigger, e) {
                                field.setValue('');
                            },
                            cls: 'x-form-clear-trigger'
                        }
                    },
                    listeners: {
                        change: 'onFilterFieldChange'
                    }
                }
            ]
        }
    ],
    listeners: {
        select: 'onSelectedTreePanelSelect'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processDoctorHasExamensViewSelectedTreePanel(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processDoctorHasExamensViewSelectedTreePanel: function(config) {
        Utility.grid.addInfoCol(this);
    }

});