/*
 * File: app/view/DoctorHasExamensViewAssociatePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DoctorHasExamensViewAssociatePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.doctorhasexamensviewassociatepanel',

    requires: [
        'MyApp.view.DoctorHasExamensViewAssociatePanelViewModel',
        'MyApp.view.DoctorHasExamensViewAssociatePanelViewController',
        'MyApp.view.DoctorHasExamensViewSelectedTreePanel',
        'MyApp.view.DoctorHasExamensViewAvailableTreePanel',
        'Ext.tree.Panel',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate'
    ],

    controller: 'doctorhasexamensviewassociatepanel',
    viewModel: {
        type: 'doctorhasexamensviewassociatepanel'
    },
    itemId: 'associatePanel',
    header: false,
    title: 'My Panel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'doctorhasexamensviewselectedtreepanel',
            reference: 'selectedTreePanel',
            flex: 1,
            listeners: {
                selectedTreeSelectEvent: 'onSelectedTreePanelSelectedTreeSelectEvent'
            }
        },
        {
            xtype: 'container',
            width: 60,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'allSelectedBtn',
                    maxWidth: 50,
                    width: 50,
                    iconCls: 'fa fa-angle-double-right',
                    listeners: {
                        click: 'onAllSelectedBtnClick'
                    }
                },
                {
                    xtype: 'tbspacer',
                    height: 10
                },
                {
                    xtype: 'button',
                    itemId: 'selectedBtn',
                    maxWidth: 50,
                    width: 50,
                    iconCls: 'fa fa-angle-right',
                    listeners: {
                        click: 'onSelectedBtnClick'
                    }
                },
                {
                    xtype: 'tbspacer',
                    height: 10
                },
                {
                    xtype: 'tbspacer',
                    height: 30
                },
                {
                    xtype: 'button',
                    itemId: 'availableBtn',
                    maxWidth: 50,
                    width: 50,
                    iconCls: 'fa fa-angle-left',
                    listeners: {
                        click: 'onAvailableBtnClick'
                    }
                },
                {
                    xtype: 'tbspacer',
                    height: 10
                },
                {
                    xtype: 'button',
                    itemId: 'allAvailableBtn',
                    maxWidth: 50,
                    width: 50,
                    iconCls: 'fa fa-angle-double-left',
                    listeners: {
                        click: 'onAllAvailableBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'doctorhasexamensviewavailabletreepanel',
            reference: 'availableTreePanel',
            flex: 1,
            listeners: {
                availableTreeSelectEvent: 'onAvailableTreePanelAvailableTreeSelectEvent'
            }
        }
    ],
    listeners: {
        afterrender: 'onAssociatePanelAfterRender',
        quitEdit: 'onAssociatePanelQuitEdit',
        resetEdit: 'onAssociatePanelResetEdit',
        saveEdit: 'onAssociatePanelSaveEdit',
        inEdit: 'onAssociatePanelInEdit'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'associateCombo',
                    fieldLabel: 'Choisir le médecin',
                    labelWidth: 150,
                    displayField: 'userFName',
                    forceSelection: true,
                    queryMode: 'local',
                    typeAhead: true,
                    valueField: 'doctorId',
                    bind: {
                        store: '{AssociateComboStore}'
                    },
                    listeners: {
                        change: 'onAssociateComboChange'
                    },
                    listConfig: {
                        xtype: 'boundlist',
                        itemSelector: 'div',
                        itemTpl: [
                            ' {userFName} {userLName}'
                        ]
                    }
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processDoctorHasExamensViewAssociatePanel(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processDoctorHasExamensViewAssociatePanel: function(config) {

         this.plugins=[];
                this.plugins.push (
                                   new Plugins.panel.TreeMultiSelect({pluginId: 'treemultiselect'}));


    }

});