/*
 * File: app/view/PriorityGridViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PriorityGridViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.prioritygrid',

    requires: [
        'Ext.data.Store'
    ],

    stores: {
        PriorityStore: {
            model: 'MyApp.model.PriorityModel'
        },
        ClientComboStore: {
            model: 'MyApp.model.ClientComboModel'
        },
        SubscriptionComboStore: {
            model: 'MyApp.model.SubscriptionComboModel'
        },
        LotComboStore: {
            model: 'MyApp.model.LotComboModel'
        },
        PortifilioComboStore: {
            model: 'MyApp.model.PortifilioComboModel'
        },
        GoAreaComboStore: {
            model: 'MyApp.model.GoAreaComboModel'
        },
        PriceTypeComboStore: {
            model: 'MyApp.model.PriceTypeComboModel'
        },
        MarketCodificationComboStore: {
            model: 'MyApp.model.MarketCodificationComboModel'
        },
        MarketCodeComboStore: {
            model: 'MyApp.model.MarketCodeComboModel'
        },
        FlowComboStore: {
            model: 'MyApp.model.FlowComboModel'
        },
        MarketCode1ComboStore: {
            model: 'MyApp.model.MarketCode1ComboModel'
        },
        PriceType1ComboStore: {
            model: 'MyApp.model.PriceType1ComboModel'
        },
        SecuritySubTypeComboStore: {
            model: 'MyApp.model.SecuritySubTypeComboModel'
        }
    }

});