/*
 * File: app/view/PriorityForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PriorityForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.priorityform',

    requires: [
        'MyApp.view.PriorityFormViewModel',
        'MyApp.view.PriorityFormViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    controller: 'priorityform',
    viewModel: {
        type: 'priorityform'
    },
    itemId: 'priorityFormId',
    bodyPadding: 10,
    header: false,
    title: '',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    listeners: {
        afterrender: 'onPriorityFormItemIdAfterRender'
    },
    items: [
        {
            xtype: 'fieldset',
            title: 'Search criteria for the rules of priority by default',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 28,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'clientComboBoxEditorItemId',
                                    width: 170,
                                    fieldLabel: 'Client',
                                    labelWidth: 55,
                                    name: 'client',
                                    selectOnFocus: true,
                                    displayField: 'client',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'clientId',
                                    bind: {
                                        store: '{ClientComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'subscriptionComboBoxEditorItemId',
                                    width: 220,
                                    fieldLabel: 'Subscription',
                                    name: 'subscription',
                                    selectOnFocus: true,
                                    displayField: 'subscription',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'subId',
                                    bind: {
                                        store: '{SubscriptionComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'portifilioComboBoxEditorItemId',
                                    width: 250,
                                    fieldLabel: 'Portifilio',
                                    labelWidth: 120,
                                    name: 'portifilio',
                                    selectOnFocus: true,
                                    displayField: 'portifilio',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'portifilioId',
                                    bind: {
                                        store: '{PortifilioComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'lotComboBoxEditorItemId',
                                    width: 180,
                                    fieldLabel: 'Lot',
                                    labelWidth: 80,
                                    name: 'lot',
                                    selectOnFocus: true,
                                    displayField: 'lot',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'lotId',
                                    bind: {
                                        store: '{LotComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'priceTypeComboBoxEditorItemId',
                                    width: 250,
                                    fieldLabel: 'Price Type',
                                    labelWidth: 120,
                                    name: 'priceType',
                                    selectOnFocus: true,
                                    displayField: 'priceType',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'priceTypeId',
                                    bind: {
                                        store: '{PriceTypeComboStore}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tbspacer',
                            height: 5
                        },
                        {
                            xtype: 'container',
                            height: 28,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'goAreaComboBoxEditorItemId',
                                    width: 170,
                                    fieldLabel: 'Go Area',
                                    labelWidth: 55,
                                    name: 'goArea',
                                    selectOnFocus: true,
                                    displayField: 'goArea',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'goAreaId',
                                    bind: {
                                        store: '{GoAreaComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'securityTypeComboBoxEditorItemId',
                                    width: 220,
                                    fieldLabel: 'Security type',
                                    name: 'securitySubType',
                                    selectOnFocus: true,
                                    displayField: 'securitySubType',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'securitySubTypeId',
                                    bind: {
                                        store: '{SecuritySubTypeComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'securitySubTypeComboBoxEditorItemId',
                                    width: 250,
                                    fieldLabel: 'Security Sub-Type',
                                    labelWidth: 120,
                                    name: 'securitySubType',
                                    selectOnFocus: true,
                                    displayField: 'securitySubType',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'securitySubTypeId',
                                    bind: {
                                        store: '{SecuritySubTypeComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'marketCodeComboBoxEditorItemId',
                                    width: 180,
                                    fieldLabel: 'Market Code',
                                    labelWidth: 80,
                                    name: 'marketCode',
                                    selectOnFocus: true,
                                    displayField: 'marketCode',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'marketCodeId',
                                    bind: {
                                        store: '{MarketCodeComboStore}'
                                    }
                                },
                                {
                                    xtype: 'tbspacer',
                                    height: 5,
                                    width: 5
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'marketCodificationComboBoxEditorItemId',
                                    width: 250,
                                    fieldLabel: 'Market Codification',
                                    labelWidth: 120,
                                    name: 'marketCodification',
                                    selectOnFocus: true,
                                    displayField: 'marketCodification',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    valueField: 'marketCodificationId',
                                    bind: {
                                        store: '{MarketCodificationComboStore}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'tbspacer',
                            height: 5
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 28,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    defaultAlign: 'b-b',
                                    width: 240,
                                    fieldLabel: '',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Role1'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Role2'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            fieldStyle: '',
                                            boxLabel: 'Role3'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'flowComboBoxEditorItemId',
                                            width: 156,
                                            fieldLabel: 'Flow',
                                            labelWidth: 35,
                                            name: 'flow',
                                            selectOnFocus: true,
                                            displayField: 'flow',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            valueField: 'flowId',
                                            bind: {
                                                store: '{FlowComboStore}'
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 5
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'priceType1ComboBoxEditorItemId',
                                            width: 250,
                                            fieldLabel: 'Price Type',
                                            labelWidth: 120,
                                            name: 'priceType1',
                                            selectOnFocus: true,
                                            displayField: 'priceType1',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            valueField: 'priceType1Id',
                                            bind: {
                                                store: '{PriceType1ComboStore}'
                                            }
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            width: 5
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'marketCode1ComboBoxEditorItemId',
                                            width: 180,
                                            fieldLabel: 'Market Code',
                                            labelWidth: 80,
                                            name: 'marketCode1',
                                            selectOnFocus: true,
                                            displayField: 'marketCode1',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            valueField: 'marketCode1Id',
                                            bind: {
                                                store: '{MarketCode1ComboStore}'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});