/*
 * File: app/view/XxLeftTreePanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.XxLeftTreePanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.xxlefttreepanel',

    onLeftTreePanelSelect: function(rowmodel, record, index, eOpts) {

        var tree=this.getView();

        Utility.tree.select(tree,record);

        this.fireViewEvent('leftTreeSelectEvent');


    },

    onFilterFieldChange: function(field, newValue, oldValue, eOpts) {
        var store=this.getViewModel().getStore('LeftTreeStore');
        Utility.tree.filter(store,newValue);
    },

    onLeftTreePanelLeftTreeSelectEvent: function() {

    }

});
