/*
 * File: app/view/ActeGrid.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ActeGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.actegrid',

    requires: [
        'MyApp.view.ActeGridViewModel',
        'MyApp.view.ActeGridViewController',
        'Ext.grid.column.Column',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel'
    ],

    controller: 'actegrid',
    viewModel: {
        type: 'actegrid'
    },
    reference: 'acteGridRef',
    itemId: 'acteGridId',
    resizable: false,
    title: '',
    forceFit: true,

    bind: {
        store: '{ActeStore}'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            width: 80,
            dataIndex: 'acteCode',
            text: 'Code',
            editor: {
                xtype: 'textfield',
                itemId: 'acteCodeTextFieldItemId',
                allowBlank: false
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return '<div style="white-space:normal">' + value + '</div>';
            },
            flex: 1,
            dataIndex: 'acteDescription',
            tdCls: 'wrap-text',
            text: 'Description',
            editor: {
                xtype: 'textareafield',
                itemId: 'acteDescriptionTextTextAreaItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            width: 80,
            dataIndex: 'acteCodeGroupement',
            text: 'Groupement',
            editor: {
                xtype: 'textfield',
                itemId: 'acteCodeGroupementTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            width: 80,
            dataIndex: 'actePrix',
            text: 'Prix',
            editor: {
                xtype: 'textfield',
                itemId: 'actePrixTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            width: 80,
            dataIndex: 'acteModificateurs',
            text: 'Modificateurs',
            editor: {
                xtype: 'textfield',
                itemId: 'acteModificateursTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'acteVersion',
            text: 'Version',
            editor: {
                xtype: 'textfield',
                itemId: 'acteVersionTextFieldItemId'
            }
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return Utility.renderer.checkBoxRenderer(value);
            },
            hidden: true,
            dataIndex: 'active',
            text: 'Active',
            editor: {
                xtype: 'checkboxfield'
            }
        }
    ],
    listeners: {
        select: 'select',
        afterrender: 'onActeGridIdAfterRender'
    },
    plugins: [
        {
            ptype: 'rowediting',
            pluginId: 'rowEdit',
            autoCancel: false,
            clicksToMoveEditor: 0,
            errorSummary: false
        }
    ],
    selModel: {
        selType: 'rowmodel',
        mode: 'SINGLE'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processActeGrid(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processActeGrid: function(config) {
        GridAddPlugins.addGridLiveSearchPlugin(this);
    }

});