/*
 * File: app/view/StudyActeGridViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StudyActeGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.studyactegrid',

    requires: [
        'MyApp.view.override.StudyActeGridViewController'
    ],

    select: function(rowmodel, record, index, eOpts) {
        // Set selected record
        //this.getViewModel().set('record', record);

        // Show details
        //this.showView('details');
    },

    onStudyActeGridIdChHist: function() {

    },

    onStudyActeGridIdAfterRender: function(component, eOpts) {


    },

    onStudyActeGridIdInEdit: function(editor, context) {

    },

    onStudyActeGridIdResetEdit: function(gridpanel, promptWin) {

    },

    onStudyActeGridIdSaveEdit: function(gridpanel, promptWin, dataToBeSaved, comment) {

    },

    onStudyActeGridIdDeleteItem: function() {

    },

    onStudyActeGridIdModifyItem: function() {

    },

    onStudyActeGridIdQuitEdit: function(gridpanel, promptWin) {

    },

    onStudyActeGridIdBeforeEdit: function(editor, context) {

    },

    onStudyActeGridIdCanceledit: function(editor, context) {

    },

    onStudyActeGridIdContainerClick: function(dataview, e, eOpts) {

    },

    onStudyActeGridIdEdit: function(editor, context) {

    },

    onStudyActeGridIdBeforeCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onStudyActeGridIdValidateedit: function(editor, context) {

    }

});
